name: Add Two Numbers

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Enter first number'
        required: true
        default: '5'
      num2:
        description: 'Enter second number'
        required: true
        default: '7'
      num3:
        description: ' Enter \n 1. Add \n 2.Sub \n 3.Mul \n 4.Divide'
        required: true
        default: '1'

jobs:
  run-add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Script
        run: python calculator.py ${{ github.event.inputs.num1 }} ${{ github.event.inputs.num2 }} ${{ github.event.inputs.num3 }}

      - name: Run add.py
        id: run-script
        run: |
          result=$(python calculator.py ${{ github.event.inputs.num1 }} ${{ github.event.inputs.num2 }} ${{ github.event.inputs.num3 }} | awk '{print $2}')
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Show result in summary
        run: echo "### The sum is ${{ steps.run-script.outputs.result }}" >> $GITHUB_STEP_SUMMARY
